### ISSUE TITLE
`AttributeError` with NumPy 2.0

### ISSUE THREAD

**Issue by CChapmanbird** [mj-will/nessai#399]
An `AttributeError` is raised when `self.state.finalise()` is called at the end of a run, because this function contains an `np.NINF` that is not supported in NumPy 2.0. This should be replaced with `-np.inf`.

**Comment by mj-will** [comment]
Hi @CChapmanbird I think this already addressed in https://github.com/mj-will/nessai/pull/387, but there isn't a release with that fix. This is probably a reason to make the release ASAP.

**Comment by mj-will** [comment]
Now that [v0.13.0](https://pypi.org/project/nessai/0.13.0/) is released, this has been addressed.
